package gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        banner = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jScrollPaneAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabelTitle = new javax.swing.JLabel();
        btnSignin = new javax.swing.JPanel();
        jLabelCreateUser = new javax.swing.JLabel();
        btnSignup = new javax.swing.JPanel();
        jLabelCancel = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        banner.setBackground(new java.awt.Color(68, 71, 90));
        banner.setLayout(null);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 51));
        txtName.setBounds(140, 80, 270, 30);
        banner.add(txtName);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        txtUsername.setBounds(140, 120, 270, 30);
        banner.add(txtUsername);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setBounds(140, 160, 270, 30);
        banner.add(txtPassword);

        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(51, 51, 51));
        txtPhoneNumber.setBounds(140, 200, 270, 30);
        banner.add(txtPhoneNumber);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setBounds(140, 240, 270, 30);
        banner.add(txtEmail);

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddress.setText("  Địa chỉ:");
        jLabelAddress.setBounds(70, 280, 70, 30);
        banner.add(jLabelAddress);

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("  Họ và tên:");
        jLabelName.setBounds(50, 80, 90, 30);
        banner.add(jLabelName);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Tên đăng nhập:");
        jLabelUsername.setBounds(20, 120, 120, 30);
        banner.add(jLabelUsername);

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Mật khẩu:");
        jLabelPassword.setBounds(60, 160, 80, 30);
        banner.add(jLabelPassword);

        jLabelPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhoneNumber.setText("   Số điện thoại:");
        jLabelPhoneNumber.setBounds(20, 200, 120, 30);
        banner.add(jLabelPhoneNumber);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("    Email:");
        jLabelEmail.setBounds(70, 240, 70, 30);
        banner.add(jLabelEmail);

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddress.setLineWrap(true);
        txtAddress.setRows(5);
        txtAddress.setAutoscrolls(false);
        txtAddress.setBorder(null);
        jScrollPaneAddress.setViewportView(txtAddress);
        jScrollPaneAddress.setBounds(140, 280, 270, 100);
        banner.add(jScrollPaneAddress);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("     Đăng ký tài khoản");
        jLabelTitle.setBounds(0, 10, 450, 40);
        banner.add(jLabelTitle);

        btnSignin.setBackground(new java.awt.Color(68, 71, 90));
        btnSignin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        btnSignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelCreateUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCreateUser.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCreateUser.setText("   Tạo tài khoản");
        jLabelCreateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnSigninLayout = new javax.swing.GroupLayout(btnSignin);
        btnSignin.setLayout(btnSigninLayout);
        btnSigninLayout.setHorizontalGroup(
            btnSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnSigninLayout.setVerticalGroup(
            btnSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        btnSignin.setBounds(140, 400, 120, 30);
        banner.add(btnSignin);

        btnSignup.setBackground(new java.awt.Color(68, 71, 90));
        btnSignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabelCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCancel.setText("           Hủy");
        jLabelCancel.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mousePressed(MouseEvent e) {
        		new Login().setVisible(true);
        		dispose();
        	}
		});

        javax.swing.GroupLayout btnSignupLayout = new javax.swing.GroupLayout(btnSignup);
        btnSignup.setLayout(btnSignupLayout);
        btnSignupLayout.setHorizontalGroup(
            btnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );
        btnSignupLayout.setVerticalGroup(
            btnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        btnSignup.setBounds(290, 400, 120, 30);
        banner.add(btnSignup);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8_close_window_20px.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.setBounds(430, 0, 20, 20);
//        banner.add(btnClose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
        	@Override
        	public void windowClosing(WindowEvent e) {
        		new Login().setVisible(true);
        		dispose();
        	}
		});
    }// </editor-fold>                        

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {           
    	new Login().setVisible(true);
        dispose();
    }                                     

    // Variables declaration - do not modify                     
    private javax.swing.JPanel banner;
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel btnSignin;
    private javax.swing.JPanel btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelCreateUser;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JScrollPane jScrollPaneAddress;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration                   
}

